export const data = [
	{
		group1: 'Health',
		group2: '',
		group3: '',
		productName: 'Cigarettes',
		turnover: 39,
		stockUnits: 122,
		stockValueRub: 4930,
		stockDays: 3.1,
		turnoverAfterLastOrder: 5.5,
	},
	{
		group1: 'Products',
		group2: 'Alcohol',
		group3: '',
		productName: 'Alcohol',
		turnover: 941,
		stockUnits: 1791,
		stockValueRub: 198300,
		stockDays: 1.9,
		turnoverAfterLastOrder: 4.7,
	},
	{
		group1: 'Products',
		group2: 'Grocery',
		group3: '',
		productName: 'Bakery goods',
		turnover: 605,
		stockUnits: 2207,
		stockValueRub: 154069,
		stockDays: 3.6,
		turnoverAfterLastOrder: 5.6,
	},
	{
		group1: '',
		group2: 'Non-alcoholic',
		group3: 'Group not specified',
		productName: 'Water',
		turnover: 128,
		stockUnits: 552,
		stockValueRub: 27983,
		stockDays: 4.3,
		turnoverAfterLastOrder: 8.6,
	},
	{
		group1: '',
		group2: 'Non-alcoholic',
		group3: '',
		productName: 'Kvass',
		turnover: 11,
		stockUnits: 52,
		stockValueRub: 2242,
		stockDays: 4.7,
		turnoverAfterLastOrder: 7.3,
	},
	{
		group1: '',
		group2: 'Non-alcoholic',
		group3: '',
		productName: 'Lemonades and carbonated drinks',
		turnover: 101,
		stockUnits: 756,
		stockValueRub: 27366,
		stockDays: 7.5,
		turnoverAfterLastOrder: 4.7,
	},
	{
		group1: 'Products',
		group2: 'Non-alcoholic',
		group3: '',
		productName: 'Juices, nectars, fruit drinks',
		turnover: 25,
		stockUnits: 177,
		stockValueRub: 6090,
		stockDays: 7.1,
		turnoverAfterLastOrder: 7.9,
	},
	{
		group1: 'Products',
		group2: 'Non-alcoholic',
		group3: 'Cold tea',
		productName: 'Lipton Lemon Tea',
		turnover: 4,
		stockUnits: 18,
		stockValueRub: 3153,
		stockDays: 4.6,
		turnoverAfterLastOrder: 4.1,
	},
	{
		group1: 'Products',
		group2: 'Non-alcoholic',
		group3: 'Cold tea',
		productName: 'Lipton Ice Tea',
		turnover: 7,
		stockUnits: 33,
		stockValueRub: 3484,
		stockDays: 4.7,
		turnoverAfterLastOrder: 9.0,
	},
	{
		group1: 'Products',
		group2: 'Non-alcoholic',
		group3: 'Energy drinks',
		productName: 'Energy drinks',
		turnover: 90,
		stockUnits: 715,
		stockValueRub: 23755,
		stockDays: 7.9,
		turnoverAfterLastOrder: 7.6,
	},
	{
		group1: 'Products',
		group2: 'Baking supplies',
		group3: '',
		productName: 'Baking supplies',
		turnover: 235,
		stockUnits: 1372,
		stockValueRub: 77677,
		stockDays: 5.8,
		turnoverAfterLastOrder: 4.9,
	},
	{
		group1: 'Products',
		group2: 'Ready meals',
		group3: '',
		productName: 'Ready meals',
		turnover: 20,
		stockUnits: 93,
		stockValueRub: 3135,
		stockDays: 4.7,
		turnoverAfterLastOrder: 5.8,
	},
	{
		group1: 'Products',
		group2: 'Frozen products',
		group3: '',
		productName: 'Frozen products',
		turnover: 66,
		stockUnits: 494,
		stockValueRub: 17308,
		stockDays: 7.5,
		turnoverAfterLastOrder: 7.1,
	},
	{
		group1: 'Products',
		group2: 'Confectionery',
		group3: '',
		productName: 'Caramel, lollipops',
		turnover: 37,
		stockUnits: 211,
		stockValueRub: 3952,
		stockDays: 5.7,
		turnoverAfterLastOrder: 7.2,
	},
	{
		group1: 'Products',
		group2: 'Dairy',
		group3: '',
		productName: 'Dairy products',
		turnover: 162,
		stockUnits: 684,
		stockValueRub: 61488,
		stockDays: 4.2,
		turnoverAfterLastOrder: 7.4,
	},
	{
		group1: 'Products',
		group2: 'Meat products',
		group3: '',
		productName: 'Meat gastronomy',
		turnover: 32,
		stockUnits: 148,
		stockValueRub: 7164,
		stockDays: 4.6,
		turnoverAfterLastOrder: 8.4,
	},
	{
		group1: 'Products',
		group2: 'Sugar',
		group3: '',
		productName: 'Sugar',
		turnover: 15,
		stockUnits: 92,
		stockValueRub: 3524,
		stockDays: 6.1,
		turnoverAfterLastOrder: 5.3,
	},
	{
		group1: 'Products',
		group2: 'Confectionery',
		group3: '',
		productName: 'Fruits and nuts in glaze, dragees',
		turnover: 13,
		stockUnits: 53,
		stockValueRub: 2435,
		stockDays: 4.1,
		turnoverAfterLastOrder: 4.6,
	},
	{
		group1: 'Products',
		group2: 'Baked goods',
		group3: '',
		productName: 'Bread and pastries',
		turnover: 83,
		stockUnits: 427,
		stockValueRub: 12544,
		stockDays: 5.2,
		turnoverAfterLastOrder: 9.0,
	},
	{
		group1: 'Products',
		group2: 'Confectionery',
		group3: '',
		productName: 'Chocolate and chocolate products',
		turnover: 85,
		stockUnits: 402,
		stockValueRub: 13652,
		stockDays: 4.7,
		turnoverAfterLastOrder: 8.2,
	},
	{
		group1: 'Products',
		group2: 'Eggs',
		group3: '',
		productName: 'Eggs',
		turnover: 10,
		stockUnits: 42,
		stockValueRub: 6995,
		stockDays: 4.2,
		turnoverAfterLastOrder: 8.7,
	},
];
